1. Implement Decision Tree Classifier for classification of Iris dataset
a. Load the data set
b. Split the data set to train and test sets
c. Train a Decision Tree using train set
d. Test the model using test set. Find accuracy and confusion Matrix.

In [11]:
pip install scikit-learn numpy seaborn matplotlib

In [12]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

a. Load the data set
b. Split the data set to train and test sets

In [13]:
iris = load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=40)

c. Train a Decision Tree using train set

In [14]:
lf = DecisionTreeClassifier()
lf.fit(X_train,y_train)

DecisionTreeClassifier()

d. Test the model using test set.



In [15]:
y_pred = lf.predict(X_test)
print(y_pred)

[0 1 2 2 1 2 1 1 1 0 1 0 0 2 1 2 2 2 1 1 2 2 1 0 1 0 0 2 0 1]


Finding accuracy and confusion Matrix.

In [16]:
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy: {accuracy * 100:2f}%")

conf_matrix = confusion_matrix(y_test,y_pred)
print("\nConfusion Matrix is: ")
print(conf_matrix)

Accuracy: 100.000000%

Confusion Matrix is: 
[[ 8  0  0]
 [ 0 12  0]
 [ 0  0 10]]
